CREATE TABLE Rest
(
        restid INTEGER unsigned AUTO_INCREEMENT NOT NULL,
        restname VARCHAR(50) DEFAULT NULL,
        picurl VARCHAR(255) NOT NULL,
        resttag VARCHAR(225) NOT NULL,
        created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
        updated TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY(albumid)
)